Repository apache/pulsar-client-node, pull requests merged in 2019-08, with the labels that each got.

#41 [Issue #39]Add skip flag for cMessageId free
  src/MessageId.cc
  src/MessageId.h
Labels: type/bug

#48 Change initial version to 0.0.1
  README.md
  package-lock.json
  package.json
Labels: type/task

#49 Bump the master version to 0.1.0
  package-lock.json
  package.json
Labels: type/task

#50 Change first release version to 1.0.0
  README.md
  package-lock.json
  package.json
Labels: type/task

#52 Update eslint-utils
  package-lock.json
Labels: type/security

#53 Bump the master version to 1.1.0
  package-lock.json
  package.json
Labels: type/task
