Repository apache/pulsar-client-node, pull requests merged in 2020-02, with the labels that each got.

#66 Support subscriptionInitialPosition setting
  src/ConsumerConfig.cc
  tests/end_to_end.test.js
Labels: type/feature

#67 Support Set Replication Clusters
  src/Message.cc
Labels: type/feature

#68 Update compatibility table with C++ client
  README.md
Labels: component/documentation

#69 Bump the master version to 1.2.0
  package-lock.json
  package.json
Labels: type/task

#74 Check code format before unit tests
  .eslintrc.json
  package-lock.json
  package.json
  run-unit-tests.sh
Labels: component/build
