Repository apache/pulsar-client-node, pull requests merged in 2021-07, with the labels that each got.

#162 Add Connection Status Support to Producer/Consumer/Reader
  index.d.ts
  pulsar-version.txt
  src/Consumer.cc
  src/Consumer.h
  src/Producer.cc
  src/Producer.h
  src/Reader.cc
  src/Reader.h
  tests/end_to_end.test.js
  tstest.ts
Labels: type/feature

#163 Use Buffer::Copy instead of Buffer::New
  src/Message.cc
Labels: type/bug

#165 Updated compatibility table in README.md
  README.md
Labels: type/task

#166 Upgrade package that has security vulnerabilities
  package-lock.json
  package.json
Labels: type/security

#167 Bump the master version to 1.5.0
  package-lock.json
  package.json
Labels: type/task
