Repository apache/pulsar-client-node, pull requests merged in 2021-12, with the labels that each got.

#182 fix: use pause and resume api to ensure orderly init listener->consumer
  src/Consumer.cc
Labels: type/bug

#183 fix: use pause and resume api to ensure orderly init listener->consumer
  src/Consumer.cc
Labels: type/bug

#185 Add v1.5.x to the table in README
  README.md
Labels: type/task, doc

#186 Update dependencies
  package-lock.json
  package.json
Labels: type/security

#184 Add tarball files to .gitignore
  .gitignore
Labels: type/task

#187 Bump the master version to 1.6.0
  package-lock.json
  package.json
Labels: type/task
