Repository apache/pulsar-client-node, pull requests merged in 2022-03, with the labels that each got.

#198 Upgrade libraries with security vulnerabilities
  package-lock.json
Labels: type/security

#197 Do not add license header to tarball file
  package.json
Labels: component/build

#202 Update pulsar node client version to 1.7.0-rc.0
  package-lock.json
  package.json
Labels: type/task

#203 Update compatibility table in README
  README.md
Labels: type/task, doc

#205 Upgrade minimist to 1.2.6
  package-lock.json
Labels: type/security, component/build
