Repository apache/pulsar-client-node, pull requests merged in 2023-02, with the labels that each got.

#292 Upgrade cpp client version to 3.1.1
  pulsar-client-cpp.txt
Labels: type/bug, release/v1.8.1, cherry-picked/branch-1.8

#293 Upgrade ansi-regex
  package-lock.json
Labels: type/security

#294 Remove unnecessary / at the end of CPP_CLIENT_BASE_URL
  pulsar-client-cpp.txt
Labels: no-need-doc

#291 Update the release process
  docs/release-process.md
Labels: release/v1.8.1, cherry-picked/branch-1.8

#295 [fix] Fix the binary host url
  package.json
Labels: release/v1.8.1

#297 Upgrade the depend on cpp version to 3.1.2.
  pulsar-client-cpp.txt
Labels: release/v1.8.1
