Repository apache/pulsar-client-node, pull requests merged in 2023-04, with the labels that each got.

#310 Fix symbols conflict of OpenSSL.
  binding.gyp
Labels: type/bug, release/v1.8.2

#313 [fix] Add tests for produce and consume with TLS enabled
  binding.gyp
  build-support/pulsar-test-container-start.sh
  build-support/pulsar-test-service-start.sh
  tests/certificate/server.crt
  tests/certificate/server.key
  tests/conf/standalone.conf
  tests/end_to_end.test.js
Labels: component/test, no-need-doc

#314 docs: add typedoc to generate apidoc
  .gitignore
  README.md
  package-lock.json
  package.json
  tests/run-unit-tests.sh
  tslint.json
  tstest.ts
  typedoc.json
Labels: doc, release/v1.8.2

#309 [Fix] Fix message listener doesn't respect receiver queue size
  src/Consumer.cc
  tests/end_to_end.test.js
Labels: type/bug, release/v1.8.3

#317 Add NOTICE file.
  NOTICE
Labels: release/v1.8.2

#319 [Improve] Add error handling for the message listener
  src/Client.h
  src/Consumer.cc
  src/Consumer.h
  src/LogUtils.h
  tests/end_to_end.test.js
Labels: release/v1.8.3
