Repository apache/pulsar-client-node, pull requests merged in 2023-03, with the labels that each got.

#302 [fix] Fix error when falling back to local build
  .github/workflows/ci-pr-validation.yml
  binding.gyp
Labels: type/bug, no-need-doc

#304 [fix] not compatible with alpine 3.15 env
  .github/workflows/ci-pr-validation.yml
  pkg/linux/Dockerfile_linux_musl
  tests/load-test.sh
Labels: type/bug, release/v1.8.2

#307 [Fix] Wrap c++ exception when creating client.
  src/Client.cc
  tests/client.test.js
Labels: release/v1.8.2
